_wandb:
    value:
        cli_version: 0.21.0
        e:
            nk7vcujj1icz462afymd1a4w7smr9ffq:
                args:
                    - --gpu_number
                    - "0"
                    - --resolution
                    - "129"
                codePath: Experiments_LOD/CNO_experiment.py
                codePathLocal: CNO_experiment.py
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1006450962432"
                        used: "914010750976"
                email: haltmayermarc@cau.ac.kr
                executable: /home/haltmayermarc/anaconda3/envs/fenics/bin/python3
                git:
                    commit: cb33f67cc2b01fdaffa0a581e238cb19f0dd78b2
                    remote: https://github.com/seojaemin22/neuraloperator.git
                gpu: NVIDIA RTX A6000
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-2193dc89-e3a8-9bbb-32b3-48fe1b96d6e6
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-dc0c0f3b-8eaf-ce8c-938a-f6ee7884cd80
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-ad00ce5a-984d-0751-4c33-c8c64a894909
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-329fcbc9-fa86-3420-b179-4958e955a084
                host: user-desktop
                memory:
                    total: "270103248896"
                os: Linux-6.8.0-86-generic-x86_64-with-glibc2.35
                program: /home/haltmayermarc/Samsung/neuraloperator/Experiments_LOD/CNO_experiment.py
                python: CPython 3.11.12
                root: /home/haltmayermarc/Samsung/neuraloperator/Experiments_LOD
                startedAt: "2025-11-12T01:59:14.538799Z"
                writerId: nk7vcujj1icz462afymd1a4w7smr9ffq
        m: []
        python_version: 3.11.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 61
            "4": 3.11.12
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
